language: node_js
node_js:
  - "10"
dist: trusty
sudo: true

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential git -y
  - sudo apt-get install libudev-dev -y
  - sudo apt-get install libusb-1.0-0-dev -y
  - sudo apt-get install gcc-4.8 g++-4.8 -y

script:
  - ng build --prod

deploy:
  provider: script
  script: npx angular-cli-ghpages --cname=vault.mynano.ninja --no-silent --name="BitDesert" --email=admin@mynano.ninja --repo=https://GH_TOKEN@github.com/BitDesert/NinjaVault
  skip_cleanup: true
  on:
    branch: master
