language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: script
  script: npx angular-cli-ghpages --cname=vault-gh.mynano.ninja --no-silent --name="BitDesert" --email=admin@mynano.ninja
  skip_cleanup: true
  on:
    branch: master
